repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v0.7.1
    hooks:
      - id: check-merge-conflict
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.0
    hooks:
      - id: prettier
        files: \.(json|yml|yaml|md|xml)$
        additional_dependencies:
          - prettier@2.3.0
          - "@prettier/plugin-xml@0.13.1"
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: make lint
        language: system
        pass_filenames: false
